import jsPDF from "jspdf";

export function generateReportPdf(report) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 50;
  let y = 60;

  // Header
  doc.setFillColor(15, 23, 42); // ink
  doc.rect(0, 0, pageWidth, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("CommunityLens AI", margin, 40);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Generated Area Report", margin, 62);

  y = 120;
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(report.area_name, margin, y);

  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const generatedDate = new Date(report.generated_at).toLocaleString();
  doc.text(`Generated: ${generatedDate}`, margin, y);

  // Risk badge
  y += 30;
  const riskColors = {
    Low: [20, 184, 166],
    Moderate: [245, 166, 35],
    High: [228, 87, 46],
    Severe: [228, 87, 46],
  };
  const [r, g, b] = riskColors[report.risk_category] || [100, 116, 139];
  doc.setFillColor(r, g, b);
  doc.roundedRect(margin, y - 14, 160, 26, 6, 6, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Risk: ${report.risk_category} (${report.risk_score}/100)`, margin + 12, y + 3);

  // Stats grid
  y += 50;
  doc.setTextColor(15, 23, 42);
  const stats = [
    ["Air Quality (AQI)", `${report.aqi_value}`],
    ["PM2.5 / PM10", `${report.pm25} / ${report.pm10}`],
    ["Traffic", `${report.congestion_level} (${report.avg_speed_kmph} km/h avg)`],
    ["Hospitals Nearby", `${report.total_hospitals}`],
    ["Beds Available", `${report.beds_available}`],
  ];

  const colWidth = (pageWidth - margin * 2) / 2;
  stats.forEach(([label, value], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = margin + col * colWidth;
    const rowY = y + row * 40;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(label.toUpperCase(), x, rowY);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(value, x, rowY + 16);
  });

  y += Math.ceil(stats.length / 2) * 40 + 20;

  // Divider
  doc.setDrawColor(230, 230, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 30;

  // Narrative
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("AI Summary", margin, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(30, 41, 59);
  const narrativeLines = doc.splitTextToSize(report.narrative, pageWidth - margin * 2);
  doc.text(narrativeLines, margin, y, { lineHeightFactor: 1.5 });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by CommunityLens AI \u2014 Gen AI Academy APAC Edition Hackathon",
    margin,
    pageHeight - 30
  );

  doc.save(`CommunityLensAI_${report.area_name.replace(/\s+/g, "_")}_Report.pdf`);
}